### ISSUE TITLE
Hash out how treasury account accumulates/withdraws fees 

### ISSUE THREAD

**Issue by shaspitz** [primev/mev-commit#273]
Currently mev-commit chain base fees accumulate directly to this [arbitrary placeholder address](https://github.com/primev/mev-commit-geth/blob/553c7c336fe185ce4c4169b6e9ad1e8e71943826/core/state_transition.go#L465). Contract fees can be withdrawn from the contracts with [this address](https://github.com/primev/mev-commit/blob/9529ee86ccd9917a19df15f0f7de8d14259edfee/contracts/scripts/DeployScripts.s.sol#L25). Neither of these accounts represent a treasury, multisig, receiver contract etc. 

We need to hash out how the treasury will work for our chain and protocol. Where are fees accumulated? How are they withdrawn? Do we implement a receiver contract? 

We'll need to decide if we have separate accounts for contract ownership and fee management, or consolidate. 

In the previous contract repo I had a draft PR which may give some inspiration here: https://github.com/primev/contracts/pull/66

**Comment by techgangboss** [comment]
Fees should accumulate on a multisig contract address, no withdraw necessary for now / no touch policy. Primev dev related multisig & accounts need to be separate from mev-commit treasury related ones

**Comment by shaspitz** [comment]
Closing in favor of https://github.com/primev/mev-commit/issues/532
