### ISSUE TITLE
Backup registrations and assets on mev-commit chain

### ISSUE THREAD

**Issue by shaspitz** [primev/mev-commit#329]
Currently we do not backup data/events specific to bidder/provider registrations that reside from the core contracts, nor the staked ETH amounts residing in those contracts. 

For mainnet we should enable either of the following solutions, such that we can reconstruct critical registration and asset data on a new evm state, in the case of an emergency scenario. 

Solution 1: Utilize frequent mev-commit chain snapshots (see https://github.com/primev/mev-commit/issues/328) to be able to restore critical data quickly. This would require that we can spin up a dev chain or similar that can make this full snapshot state quickly accessible (under 1 hour). 

Solution 2: Create an off-chain listener service that listens for specific events `ProviderRegistered`, `BidderRegistered` etc. and store entries for each one of these events in a db. Upon needing to restore critical state, we simply query the service for relevant data to send in new registration txes. This would also require a change that we enable the core contracts to accept bidder/provider registrations from an owner/admin account (on others behalf).

**Comment by kant777** [comment]
we need to make sure the core contracts can paused
